# Generated by Django 4.2.9 on 2026-03-12 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('periodo_atual', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('trancado', 'Trancado'), ('evadido', 'Evadido'), ('formado', 'Formado')], default='ativo', max_length=10)),
                ('ano_curriculo', models.PositiveIntegerField()),
                ('carga_horaria_total', models.PositiveIntegerField(default=0)),
                ('carga_horaria_cumprida', models.PositiveIntegerField(default=0)),
                ('carga_horaria_pendente', models.PositiveIntegerField(default=0)),
                ('carga_horaria_semestre', models.PositiveIntegerField(default=0)),
                ('coeficiente', models.FloatField(default=0.0)),
                ('data_nascimento', models.DateField()),
                ('data_ingresso', models.DateField()),
                ('previsao_formatura', models.DateField()),
                ('campus', models.CharField(default='Santa Helena', max_length=100)),
                ('curso', models.CharField(default='Ciência da Computação', max_length=200)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['registro'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('carga_horaria', models.PositiveIntegerField()),
                ('periodo', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('obrigatoria', 'Obrigatória'), ('optativa', 'Optativa')], max_length=15)),
                ('grupo', models.CharField(blank=True, help_text='Grupo de optativas, ex: [412]', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['periodo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aprovada', 'Aprovada'), ('reprovada', 'Reprovada'), ('cursando', 'Cursando'), ('nao_iniciada', 'Não Iniciada')], default='nao_iniciada', max_length=15)),
                ('nota', models.FloatField(blank=True, null=True)),
                ('frequencia', models.PositiveSmallIntegerField(blank=True, help_text='Percentual de presença', null=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='core.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='core.disciplina')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['disciplina__periodo', 'disciplina__codigo'],
                'unique_together': {('aluno', 'disciplina')},
            },
        ),
    ]
