# Generated by Django 4.2.9 on 2026-03-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='areas_mentoria',
            field=models.TextField(blank=True, help_text='Áreas de expertise para mentoria (separadas por comma)', null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cargo',
            field=models.CharField(blank=True, help_text='Cargo/Posição atual do egresso', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='disponibilidade',
            field=models.CharField(choices=[('alta', 'Muito disponível'), ('media', 'Moderadamente disponível'), ('baixa', 'Pouco disponível')], default='media', help_text='Disponibilidade para mentoria', max_length=10),
        ),
        migrations.AddField(
            model_name='aluno',
            name='empresa',
            field=models.CharField(blank=True, help_text='Empresa atual do egresso', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='trabalha_remoto',
            field=models.BooleanField(default=False, help_text='Trabalha em modelo remoto'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
