# Generated by Django 4.2.9 on 2026-03-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aluno_areas_mentoria_aluno_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Acesso ao painel administrativo'),
        ),
    ]
