// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env.DATABASE_URL,
    // Only used by `prisma migrate diff` against the migrations dir; harmless
    // otherwise. Points at a throwaway DB created on demand for diffing.
    shadowDatabaseUrl: process.env.SHADOW_DATABASE_URL,
  },
});
