// Curated icon set for gamification content (achievements, track nodes).
// Keys are the kebab-case lucide names stored in the DB (same convention the
// Fase 3 seed uses in gamification-base.json). Explicit imports keep the
// client bundle small — do NOT import the whole lucide icon map.
import {
  Award,
  Binary,
  Bird,
  Blocks,
  BookOpen,
  Brain,
  Briefcase,
  Bug,
  Calculator,
  ClipboardCheck,
  Code,
  Compass,
  Cpu,
  Crown,
  Database,
  Dna,
  Flag,
  FlaskConical,
  Footprints,
  Gem,
  Globe,
  GraduationCap,
  Handshake,
  Leaf,
  Lightbulb,
  type LucideIcon,
  Medal,
  Microscope,
  Mountain,
  Network,
  PenTool,
  Presentation,
  Puzzle,
  Rocket,
  Satellite,
  School,
  Shield,
  Sparkles,
  Sprout,
  Star,
  Target,
  TreePine,
  Trophy,
  Users,
  Wheat,
  Zap,
} from "lucide-react";

export const ICON_SET: Record<string, LucideIcon> = {
  award: Award,
  binary: Binary,
  bird: Bird,
  blocks: Blocks,
  "book-open": BookOpen,
  brain: Brain,
  briefcase: Briefcase,
  bug: Bug,
  calculator: Calculator,
  "clipboard-check": ClipboardCheck,
  code: Code,
  compass: Compass,
  cpu: Cpu,
  crown: Crown,
  database: Database,
  dna: Dna,
  flag: Flag,
  "flask-conical": FlaskConical,
  footprints: Footprints,
  gem: Gem,
  globe: Globe,
  "graduation-cap": GraduationCap,
  handshake: Handshake,
  leaf: Leaf,
  lightbulb: Lightbulb,
  medal: Medal,
  microscope: Microscope,
  mountain: Mountain,
  network: Network,
  "pen-tool": PenTool,
  presentation: Presentation,
  puzzle: Puzzle,
  rocket: Rocket,
  satellite: Satellite,
  school: School,
  shield: Shield,
  sparkles: Sparkles,
  sprout: Sprout,
  star: Star,
  target: Target,
  "tree-pine": TreePine,
  trophy: Trophy,
  users: Users,
  wheat: Wheat,
  zap: Zap,
};

export const ICON_NAMES = Object.keys(ICON_SET);

/// Fallback for icon names outside the curated set (e.g. hand-edited seeds).
export function resolveIcon(name: string | null | undefined): LucideIcon {
  return (name && ICON_SET[name]) || Sparkles;
}
